# Generated by Django 3.2.16 on 2022-11-07 16:29

import Core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='upload',
            field=models.ImageField(default=None, upload_to='uploads/%Y/%m'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(help_text='Описание должно быть больше 2х слов и содержать слова "превосходно, роскошно"', validators=[Core.validators.validate]),
        ),
    ]
