# Generated by Django 3.2.16 on 2022-11-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_item_is_on_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='upload',
            field=models.ImageField(blank=True, default=None, upload_to='uploads/%Y/%m'),
        ),
    ]
