# Generated by Django 3.2.16 on 2022-11-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20221107_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='upload',
            field=models.ImageField(blank=True, upload_to='uploads/%Y/%m'),
        ),
    ]
