# Generated by Django 3.2.16 on 2022-11-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_item_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='upload',
            field=models.ImageField(blank=True, default='uploads/logo.png', upload_to='uploads/%Y/%m'),
        ),
    ]
